version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "9200:9200"  # Expose port 9200 for Elasticsearch
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "nginx"

  vulnerable-web-app:
    image: vulnerables/web-dvwa
    environment:
      - VIRTUAL_HOST=web.local
      - VIRTUAL_PORT=80
    expose:
      - "80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    expose:
      - "9200"

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/buffer:/fluentd/buffer
    env_file:
      - ./fluentd/.env
    environment:
      - FLUENTD_CONF=fluent.conf
